### PR TITLE
chore: build multiple image types (and no target arch api)

### LINKED ISSUE #216: Ability to select multiple image types in one pass
### Is your enhancement related to a problem? Please describe

bootc makes it easy to target multiple platforms with a single container image. Yet the plugin makes me create disk images for a single platform at a time which is time consuming for the user.

### Describe the solution you'd like

Maybe changing the radial button to a check box and being able to select multiple image types and have the extension handle queuing them up to BIB on the user's behalf. 

### Describe alternatives you've considered

_No response_

### Additional context

"I need a Qcow2, ami, and vmdk. ......tada!!!"  :)

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Provide the ability to specify multiple image types at a time. Changed the build type from a string to a typed enum array and propagated the change everywhere.

Changing to an enum allowed me to remove the 'Invalid image format' error message, and for now I changed it to loop over all types to check for any existing files for the warning. Changed the radio buttons in the UI to checkboxes to allow multiple selection.

I removed the 'bootc.build.image.location' and 'bootc.build.type' labels from the container (and imagePath parameter to createBuilderImageOptions) since we don't use them, and they don't make sense/would have to be different when you're building multiple image types.

Since it was very closely aligned and would create overlapping PRs, I included the change I started coding this for: changing the API to allow not specifying a target architecture, which causes the --target-arch parameter to not be passed to the cli. No support exists in the frontend, this might be provided later as a fix or temporary workaround for #149.

### Screenshot / video of UI

Screenshot 2024-03-21 at 5 44 54 PM

### What issues does this PR fix or reference?

Fixes #216.

### How to test this PR?

Tests updated. Select multiple image types. Build!

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM, works like a charm, thank you!

**Review by cdrage — CHANGES_REQUESTED** [review]
Screenshot 2024-03-22 at 9 06 40 AM

This is unfortunately causing dashboard issues due to how I added the "addOrUpdate" functionality where it would pick based on type, arch, image, etc:

https://github.com/containers/podman-desktop-extension-bootc/blob/main/packages/backend/src/history.ts#L55

We previously discussed on adding a "build name" for each build.

Let's keep this PR open until we have https://github.com/containers/podman-desktop-extension-bootc/issues/201 fixed

**Comment by deboer-tim** [comment]
Rebased on main. Sorry for using build to do linting :), but there were several one-line changes required after rebasing. @cdrage ready for another review.

**Review by cdrage — CHANGES_REQUESTED** [review]
So only one fix and it's actually unrelated to this PR as it was introduced by the 'id' being changed / added.

When you go to build, it will "timeout" and error out, even though the container was successfully created.

This is because https://github.com/deboer-tim/podman-desktop-extension-bootc/blob/36311c0facc83e57bef0e0558f48034a24968653/packages/frontend/src/Build.svelte#L107 

I had forgotten to also make the change to Build.svelte for searching for history based upon ID rather than arch, type, etc.

Can you change that code to:

```ts
      const found = historyInfo.find(
        info =>
          info.id === buildID,
      );
 ```
 
 Once done, LGTM!

**Comment by deboer-tim** [comment]
Rebased on main due to conflict, made the Build.svelte change and one more in history.ts that I noticed while testing.

**Review by cdrage — APPROVED** [review]
Tested, works, LGTM code-wise as well.

**Pull request merged**
