### PR TITLE
Update README.md add videos and pictures

### PR DESCRIPTION
**Pull request by cdrage**
Update README.md add videos and pictures

Updates the README.md to add pictures and videos and a more in-depth
explanation for the extension.

Closes https://github.com/containers/podman-desktop-extension-bootc/issues/57

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
we should avoid to store any videos in the git repository

**Comment by cdrage** [comment]
DO NOT MERGE UNTIL:
 
 https://quay.io/bootsy/bootc-extension is publically accessible.
 
 Can you flip the switch to make it public @benoitf ?

**Comment by benoitf** [comment]
@cdrage we should publish to ghcr.io now

**Comment by benoitf** [comment]
I mean, the image

**Comment by cdrage** [comment]
> @cdrage we should publish to ghcr.io now

Are you able to set it up? I don't believe I have permissions for the correct repo. Let me know which org / repo you choose and I can update the README.md

For the README.md I've updated it to use images / videos from the github storage rather than our own doc.

**Comment by benoitf** [comment]
@cdrage https://github.com/containers/podman-desktop-extension-bootc/pull/56

**Comment by slemeur** [comment]
Thank you @cdrage for working on this documentation!

**Comment by benoitf** [comment]
@cdrage https://github.com/containers/podman-desktop-extension-bootc/pkgs/container/podman-desktop-extension-bootc

**Comment by cdrage** [comment]
I've updated the README with the new link, and I can confirm I'm able to pull / install it now (see the new video I've added to the README):

https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/99cad4b3-77b9-4118-85e9-e785c26641ec

**Review by benoitf — APPROVED** [review]

**Pull request merged**
