### PR TITLE
chore(tests): add e2e tests to bootc repo

### PR DESCRIPTION
**Pull request by cbr7**
Signed-off-by: Vladimir Lazar <vlazar@redhat.com>

### What does this PR do?

Moves bootc e2e tests from PD to extension repo

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop-extension-bootc/issues/117
https://github.com/containers/podman-desktop-extension-bootc/issues/162

### How to test this PR?

Tests need to be run from PD repo with npm script after https://github.com/containers/podman-desktop/pull/5797 is merged into main repo

### CODE REVIEW

**Comment by cbr7** [comment]
I've moved the test file into this repo as requested in https://github.com/containers/podman-desktop/pull/5797, obviously it cannot be compiled in this repo since it's missing all the dependencies, but the file is only stored here, it will be copied via npm script when executed from PD repo.

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
@cbr7 sign the commit please to pass DCO. Otherwise I would like to see this work on CI (if possible).

**Comment by cbr7** [comment]
@odockal had to rebase to do it but managed it, but the linter requirements fail, which... of course they do since it's undefined code

**Comment by cbr7** [comment]
@cdrage @deboer-tim I've added the test file to this repo as requested, but the linter build conditions all fail, which is normal since the rest of the test automation framework is in PD repo, so I'm not sure how you want to handle this in order to get it merged.

To be clear the current solution is just to store the tests in this repo, but CICD would pull both repos and copy the test file into the PD via npm script before running the tests.

**Comment by deboer-tim** [comment]
> @cdrage @deboer-tim I've added the test file to this repo as requested, but the linter build conditions all fail, which is normal since the rest of the test automation framework is in PD repo, so I'm not sure how you want to handle this in order to get it merged.
>
> To be clear the current solution is just to store the tests in this repo, but CICD would pull both repos and copy the test file into the PD via npm script before running the tests.
> 
> Conversation and request for this can be found in [containers/podman-desktop#5797](https://github.com/containers/podman-desktop/pull/5797)

I'm assuming the long term plan is similar to the Podman Desktop API, where the Podman Desktop tests (or just the core test framework/classes) are published as their own module? If so, then at that point we'd be able to have a package.json dependency, yarn/lint would pick it up, and everything would be happy.

Prior to that point I'm ok with temporary ugliness to start getting the tests executing. e.g. I'd be ok to start if we filtered the /tests folder from linting and had a manual way to kick it off.  Then the tests themselves could be run and expanded on while we figure out how to automate and clean up.

**Comment by cbr7** [comment]
@deboer-tim yes, that is correct. The plan is to move the test automation framework out of the podman desktop repo and publish it as it's own npm module, which can then be imported and used everywhere else.

**Pull request merged**
