### PR TITLE
[wip / do not merge] feat: form page / webview component for bootc

### PR DESCRIPTION
**Pull request by cdrage**
feat: form page / webview component for bootc

### What does this PR do?

Our first ever form page!

This is a massive PR / "initiliazation" PR to get our form page started.

It includes some basic features and a working, functional form page
that:

* Checks what images are available / listed and filters out non-bootc
  ones
* Submit it and have it running in the background

There are also some significant architectural changes:
* Shared / frontend / backend folders that demonstrate each section of
  the extension, in order to do cross-communication between the webview
  and backend
* Refactoring of the "quickpick" so it is now separate from the other
  functionalities of the extension and is still useable. It is now in a
  separate function that just gets the users input from quickpick

To note:

* There may be some validation that is still needed / to test / try to
  "break" the form

### Screenshot / video of UI

https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/595b881c-0d11-4f01-a0ae-4dc76470b6a3

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop-extension-bootc/issues/141

### How to test this PR?

1. `yarn watch` or `yarn build` in the extension folder
2. You MAY have to do `yarn install` or `yarn` in both the root folder,
   and `packages/frontend` and `packages/backend` for it to work
   correctly.
3. Go to the LATEST changes on the main branch of podman desktop, and
   run `yarn watch --extension-folder ../bootc/packages/backend`

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
Some other notes which are covered in different issues:
* https://github.com/containers/podman-desktop-extension-bootc/issues/154
* https://github.com/containers/podman-desktop-extension-bootc/issues/155
* https://github.com/containers/podman-desktop-extension-bootc/issues/156

**Comment by benoitf** [comment]
hello, to avoid the `This is a massive PR / "initiliazation" PR`

could you do iterative stuff

for example, move the current code to a backend package (no code change except the move to a subfolder)
then you can introduce frontend module (can be empty and not used)
etc

so lot of stuff could already be merged

**Comment by benoitf** [comment]
> Will do! This is just a draft / WIP to show progress.

yes but usually when you'll reach the end of the draft it will result in a PR being too big
so you should start to issue small chunks as soon as possible.

new directories, new dependencies, etc, all of that could already be started to be integrated without breaking the current behaviour

**Comment by cdrage** [comment]
> > Will do! This is just a draft / WIP to show progress.
> 
> 
> 
> yes but usually when you'll reach the end of the draft it will result in a PR being too big
> 
> so you should start to issue small chunks as soon as possible.
> 
> 
> 
> new directories, new dependencies, etc, all of that could already be started to be integrated without breaking the current behaviour

I understand, this is just a WIP / draft with all the code and intended changes for demo purposes. 

This will be pushed in multiple other PRs in the future.

**Comment by cdrage** [comment]
I am closing this PR for now @feloy so that this does not cluster up the PR list.

Expect some smaller PR's next week 👍

**Pull request closed without merging**
